version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /archlinux
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /debian
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /gentoo
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /rpm
    schedule:
      interval: daily
